### ISSUE TITLE
pls update to null-Safety

### ISSUE THREAD

**Issue by xuziwei1111** [bladeofgod/throw_cart_demo#4]
pls update to null-Safety

**Comment by callmejm** [comment]
+1

**Comment by WellerZhao** [comment]
try this:

```
  add_cart_parabola:
    git:
      ref: 0.1.0
      url: https://github.com/WellerZhao/add_cart_parabola.git
```
